// T-6A Ops Limits Questions
// Based on official T-6A Operating Limitations

export const opsLimitsQuestions = {
  multipleChoice: [
    // Maximum Torque
    {
      id: "ops-mc-001",
      category: "Engine Limits",
      topic: "Torque",
      difficulty: "medium",
      question: "What is the maximum torque for takeoff/max power?",
      options: ["95%", "100%", "105%", "107%"],
      correctAnswer: 1,
      explanation: "Maximum torque for takeoff/max power is 100%.",
      limitation: true,
    },
    {
      id: "ops-mc-002",
      category: "Engine Limits",
      topic: "Torque",
      difficulty: "high",
      question: "What is the transient torque limit and duration?",
      options: ["101% to 105% (3 sec)", "101% to 107% (5 sec)", "101% to 110% (10 sec)", "105% to 107% (5 sec)"],
      correctAnswer: 1,
      explanation: "Transient torque limit is 101% to 107% for 5 seconds.",
      limitation: true,
    },
    {
      id: "ops-mc-003",
      category: "Engine Limits",
      topic: "Torque",
      difficulty: "critical",
      question: "Torque above what percentage is indicative of a system malfunction?",
      options: ["100%", "105%", "107%", "110%"],
      correctAnswer: 2,
      explanation: "Torque above 107% is indicative of a system malfunction.",
      limitation: true,
    },

    // Maximum ITT
    {
      id: "ops-mc-004",
      category: "Engine Limits",
      topic: "ITT",
      difficulty: "medium",
      question: "What is the maximum ITT at idle?",
      options: ["700°C", "750°C", "820°C", "870°C"],
      correctAnswer: 1,
      explanation: "Maximum ITT at idle is 750°C.",
      limitation: true,
    },
    {
      id: "ops-mc-005",
      category: "Engine Limits",
      topic: "ITT",
      difficulty: "medium",
      question: "What is the maximum ITT for takeoff/max power?",
      options: ["750°C", "820°C", "870°C", "1000°C"],
      correctAnswer: 1,
      explanation: "Maximum ITT for takeoff/max power is 820°C.",
      limitation: true,
    },
    {
      id: "ops-mc-006",
      category: "Engine Limits",
      topic: "ITT",
      difficulty: "high",
      question: "What is the transient ITT limit and duration?",
      options: ["750-820°C (10 sec)", "821-870°C (20 sec)", "871-1000°C (5 sec)", "820-870°C (30 sec)"],
      correctAnswer: 1,
      explanation: "Transient ITT limit is 821 to 870°C for 20 seconds.",
      limitation: true,
    },

    // N1 Limits
    {
      id: "ops-mc-007",
      category: "Engine Limits",
      topic: "N1",
      difficulty: "medium",
      question: "What is the N1 idle range on the ground?",
      options: ["55-60%", "60-61%", "62-67%", "67-70%"],
      correctAnswer: 1,
      explanation: "N1 idle is 60 to 61% on the ground. Minimum N1 in flight is 67%.",
      limitation: true,
    },
    {
      id: "ops-mc-008",
      category: "Engine Limits",
      topic: "N1",
      difficulty: "medium",
      question: "What is the minimum N1 in flight?",
      options: ["60%", "61%", "65%", "67%"],
      correctAnswer: 3,
      explanation: "Minimum N1 in flight is 67%.",
      limitation: true,
    },

    // Np Limits
    {
      id: "ops-mc-009",
      category: "Engine Limits",
      topic: "Np",
      difficulty: "medium",
      question: "What is the Np idle range?",
      options: ["40-45%", "46-50%", "55-60%", "60-65%"],
      correctAnswer: 1,
      explanation: "Np idle range is 46 to 50%.",
      limitation: true,
    },
    {
      id: "ops-mc-010",
      category: "Engine Limits",
      topic: "Np",
      difficulty: "medium",
      question: "What is the Np for takeoff/max power?",
      options: ["98%", "100%", "102%", "105%"],
      correctAnswer: 1,
      explanation: "Np for takeoff/max power is 100% (100% +/- 2% with PMU off).",
      limitation: true,
    },
    {
      id: "ops-mc-011",
      category: "Engine Limits",
      topic: "Np",
      difficulty: "high",
      question: "What Np range should be avoided during stabilized ground operations?",
      options: ["50-60%", "62-80%", "80-90%", "90-100%"],
      correctAnswer: 1,
      explanation: "Avoid stabilized ground operations from 62 to 80% Np due to resonance.",
      limitation: true,
    },

    // Oil Pressure
    {
      id: "ops-mc-012",
      category: "Engine Limits",
      topic: "Oil Pressure",
      difficulty: "medium",
      question: "What is the oil pressure range for takeoff/max power?",
      options: ["40-80 PSI", "60-100 PSI", "90-120 PSI", "100-150 PSI"],
      correctAnswer: 2,
      explanation: "Oil pressure for takeoff/max power is 90 to 120 PSI.",
      limitation: true,
    },
    {
      id: "ops-mc-013",
      category: "Engine Limits",
      topic: "Oil Pressure",
      difficulty: "high",
      question: "What is the oil pressure range for aerobatics/spins?",
      options: ["40-80 PSI", "40-130 PSI", "90-120 PSI", "90-150 PSI"],
      correctAnswer: 1,
      explanation: "Oil pressure for aerobatics/spins is 40 to 130 PSI.",
      limitation: true,
    },
    {
      id: "ops-mc-014",
      category: "Engine Limits",
      topic: "Oil Pressure",
      difficulty: "high",
      question: "What is the oil pressure range for aerobatics/spins at idle?",
      options: ["10-30 PSI", "15-40 PSI (5 sec)", "40-60 PSI", "60-90 PSI"],
      correctAnswer: 1,
      explanation: "Oil pressure for aerobatics/spins at idle is 15 to 40 PSI for 5 seconds.",
      limitation: true,
    },

    // Oil Temperature
    {
      id: "ops-mc-015",
      category: "Engine Limits",
      topic: "Oil Temperature",
      difficulty: "medium",
      question: "What is the oil temperature range for takeoff/max power?",
      options: ["0-100°C", "10-105°C", "10-110°C", "20-110°C"],
      correctAnswer: 1,
      explanation: "Oil temperature for takeoff/max power is 10 to 105°C.",
      limitation: true,
    },
    {
      id: "ops-mc-016",
      category: "Engine Limits",
      topic: "Oil Temperature",
      difficulty: "high",
      question: "What is the transient oil temperature limit and duration?",
      options: ["105-110°C (5 min)", "106-110°C (10 min)", "110-115°C (5 min)", "110-120°C (10 min)"],
      correctAnswer: 1,
      explanation: "Transient oil temperature is 106 to 110°C for 10 minutes.",
      limitation: true,
    },

    // Fuel Flow
    {
      id: "ops-mc-017",
      category: "Engine Limits",
      topic: "Fuel Flow",
      difficulty: "medium",
      question: "What is the maximum fuel flow for all phases of flight?",
      options: ["699 PPH", "750 PPH", "799 PPH", "850 PPH"],
      correctAnswer: 2,
      explanation: "Maximum fuel flow for all phases of flight is 799 PPH.",
      limitation: true,
    },

    // Prohibited Maneuvers
    {
      id: "ops-mc-018",
      category: "Prohibited Maneuvers",
      topic: "Spins",
      difficulty: "critical",
      question: "Which type of stalls are prohibited?",
      options: ["Accelerated stalls", "Power-on stalls", "Inverted stalls", "Approach stalls"],
      correctAnswer: 2,
      explanation: "Inverted stalls are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-019",
      category: "Prohibited Maneuvers",
      topic: "Spins",
      difficulty: "critical",
      question: "Which type of spins are prohibited?",
      options: ["Erect spins", "Inverted spins", "Flat spins", "Steep spins"],
      correctAnswer: 1,
      explanation: "Inverted spins are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-020",
      category: "Prohibited Maneuvers",
      topic: "Spins",
      difficulty: "critical",
      question: "Aggravated spins past how many turns are prohibited?",
      options: ["1 turn", "2 turns", "3 turns", "4 turns"],
      correctAnswer: 1,
      explanation: "Aggravated spins past 2 turns are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-021",
      category: "Prohibited Maneuvers",
      topic: "Spins",
      difficulty: "critical",
      question: "What is prohibited regarding PCL position during spins?",
      options: ["PCL at idle", "PCL at mid-range", "PCL above idle", "PCL at cutoff"],
      correctAnswer: 2,
      explanation: "Spins with the PCL above idle are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-022",
      category: "Prohibited Maneuvers",
      topic: "Configuration",
      difficulty: "critical",
      question: "Spins with which of the following extended are prohibited?",
      options: ["Landing gear only", "Flaps only", "Landing gear, flaps, or speed brake", "Speed brake only"],
      correctAnswer: 2,
      explanation: "Spins with the landing gear, flaps, or speed brake extended are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-023",
      category: "Prohibited Maneuvers",
      topic: "Systems",
      difficulty: "critical",
      question: "Spins with what system off are prohibited?",
      options: ["Autopilot", "PMU", "OBOGS", "Fuel pump"],
      correctAnswer: 1,
      explanation: "Spins with the PMU off are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-024",
      category: "Prohibited Maneuvers",
      topic: "Altitude",
      difficulty: "critical",
      question: "Spins below what altitude are prohibited?",
      options: ["5,000 ft PA", "8,000 ft PA", "10,000 ft PA", "13,500 ft MSL"],
      correctAnswer: 2,
      explanation: "Spins below 10,000 feet pressure altitude are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-025",
      category: "Prohibited Maneuvers",
      topic: "Altitude",
      difficulty: "critical",
      question: "Spins above what altitude are prohibited?",
      options: ["18,000 ft PA", "20,000 ft PA", "22,000 ft PA", "25,000 ft PA"],
      correctAnswer: 2,
      explanation: "Spins above 22,000 feet pressure altitude are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-026",
      category: "Prohibited Maneuvers",
      topic: "Maneuvers",
      difficulty: "critical",
      question: "What type of maneuvering is prohibited?",
      options: ["Barrel rolls", "Loops", "Abrupt cross-controlled (snap) maneuvers", "Aileron rolls"],
      correctAnswer: 2,
      explanation: "Abrupt cross-controlled (snap) maneuvers are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-027",
      category: "Prohibited Maneuvers",
      topic: "Fuel",
      difficulty: "high",
      question: "Aerobatic maneuvers with greater than how many pounds fuel imbalance are prohibited?",
      options: ["25 lbs", "50 lbs", "75 lbs", "100 lbs"],
      correctAnswer: 1,
      explanation: "Aerobatic maneuvers, spins, or stalls with greater than 50 pounds fuel imbalance are prohibited.",
      limitation: true,
    },
    {
      id: "ops-mc-028",
      category: "Prohibited Maneuvers",
      topic: "Maneuvers",
      difficulty: "critical",
      question: "What type of slides are prohibited?",
      options: ["Side slides", "Tail slides", "Forward slides", "Slip slides"],
      correctAnswer: 1,
      explanation: "Tail slides are prohibited.",
      limitation: true,
    },

    // Airspeed Limitations
    {
      id: "ops-mc-029",
      category: "Airspeed Limits",
      topic: "Gear/Flaps",
      difficulty: "high",
      question: "What is the maximum airspeed with gear and/or flaps extended?",
      options: ["120 KIAS", "130 KIAS", "150 KIAS", "175 KIAS"],
      correctAnswer: 2,
      explanation: "Maximum airspeed with gear and/or flaps extended is 150 KIAS.",
      limitation: true,
    },
    {
      id: "ops-mc-030",
      category: "Airspeed Limits",
      topic: "Operating Speed",
      difficulty: "medium",
      question: "What is the maximum operating speed?",
      options: ["300 KIAS or 0.65 Mach", "316 KIAS or 0.67 Mach", "320 KIAS or 0.70 Mach", "350 KIAS or 0.75 Mach"],
      correctAnswer: 1,
      explanation: "Maximum operating speed is 316 KIAS or 0.67 Mach, whichever is lower.",
      limitation: true,
    },
    {
      id: "ops-mc-031",
      category: "Airspeed Limits",
      topic: "Rudder",
      difficulty: "high",
      question: "Full rudder deflection above what airspeed will exceed rudder control system limits?",
      options: ["120 KIAS", "135 KIAS", "150 KIAS", "175 KIAS"],
      correctAnswer: 2,
      explanation: "Full rudder deflection above 150 KIAS will exceed the limits of the rudder control system.",
      limitation: true,
    },

    // Starting Limits
    {
      id: "ops-mc-032",
      category: "Starting Limits",
      topic: "Starter",
      difficulty: "medium",
      question: "What is the starter time limit?",
      options: ["10 sec", "20 sec", "30 sec", "60 sec"],
      correctAnswer: 1,
      explanation: "Starter limit is 20 seconds.",
      limitation: true,
    },
    {
      id: "ops-mc-033",
      category: "Starting Limits",
      topic: "Wait Times",
      difficulty: "high",
      question: "How long must you wait after each start/motoring attempt?",
      options: ["15 sec, 1 min, 3 min, 15 min", "30 sec, 2 min, 5 min, 30 min", "45 sec, 3 min, 10 min, 45 min", "60 sec, 5 min, 15 min, 60 min"],
      correctAnswer: 1,
      explanation: "Wait 30 seconds, 2 minutes, 5 minutes, then 30 minutes after each start/motoring attempt.",
      limitation: true,
    },
    {
      id: "ops-mc-034",
      category: "Starting Limits",
      topic: "ITT",
      difficulty: "critical",
      question: "What is the maximum ITT during restart (do not attempt restart if exceeded)?",
      options: ["820°C", "850°C", "871 to 1,000°C for 5 sec", "1,000°C"],
      correctAnswer: 2,
      explanation: "Maximum ITT for restart is 871 to 1,000°C for 5 seconds. Do not attempt restart if this is exceeded.",
      limitation: true,
    },
    {
      id: "ops-mc-035",
      category: "Starting Limits",
      topic: "Oil Pressure",
      difficulty: "medium",
      question: "What is the maximum oil pressure during start?",
      options: ["150 PSI", "175 PSI", "200 PSI", "225 PSI"],
      correctAnswer: 2,
      explanation: "Maximum oil pressure during start is 200 PSI.",
      limitation: true,
    },
    {
      id: "ops-mc-036",
      category: "Starting Limits",
      topic: "Oil Temperature",
      difficulty: "medium",
      question: "What is the minimum oil temperature for start?",
      options: ["-50°C", "-40°C", "-30°C", "-20°C"],
      correctAnswer: 1,
      explanation: "Minimum oil temperature for start is -40°C.",
      limitation: true,
    },
    {
      id: "ops-mc-037",
      category: "Starting Limits",
      topic: "Battery",
      difficulty: "medium",
      question: "What is the minimum battery voltage for start?",
      options: ["22.0 V", "23.0 V", "23.5 V", "24.0 V"],
      correctAnswer: 2,
      explanation: "Minimum battery voltage for start is 23.5 V.",
      limitation: true,
    },

    // Pressurization
    {
      id: "ops-mc-038",
      category: "Pressurization",
      topic: "Normal",
      difficulty: "medium",
      question: "What is the normal cabin pressurization above 18,000 ft MSL?",
      options: ["3.0 +/- 0.2 PSI", "3.6 +/- 0.2 PSI", "4.0 +/- 0.2 PSI", "5.0 +/- 0.2 PSI"],
      correctAnswer: 1,
      explanation: "Normal pressurization above 18,000 ft MSL is 3.6 +/- 0.2 PSI.",
      limitation: true,
    },
    {
      id: "ops-mc-039",
      category: "Pressurization",
      topic: "Safety Valve",
      difficulty: "medium",
      question: "At what pressure does the overpressurization safety valve open?",
      options: ["3.6 PSI", "3.8 PSI", "4.0 PSI", "4.5 PSI"],
      correctAnswer: 2,
      explanation: "The overpressurization safety valve opens at 4.0 PSI.",
      limitation: true,
    },

    // Fuel
    {
      id: "ops-mc-040",
      category: "Fuel Limits",
      topic: "Recovery",
      difficulty: "medium",
      question: "What is the normal recovery fuel?",
      options: ["150 lbs", "200 lbs", "250 lbs", "300 lbs"],
      correctAnswer: 1,
      explanation: "Normal recovery fuel is 200 pounds.",
      limitation: true,
    },
    {
      id: "ops-mc-041",
      category: "Fuel Limits",
      topic: "Minimum",
      difficulty: "high",
      question: "What is the minimum fuel (dual crew)?",
      options: ["100 lbs", "150 lbs", "200 lbs", "250 lbs"],
      correctAnswer: 1,
      explanation: "Minimum fuel is 150 pounds dual (200 pounds solo).",
      limitation: true,
    },
    {
      id: "ops-mc-042",
      category: "Fuel Limits",
      topic: "Emergency",
      difficulty: "high",
      question: "What is the emergency fuel level?",
      options: ["50 lbs", "100 lbs", "150 lbs", "200 lbs"],
      correctAnswer: 1,
      explanation: "Emergency fuel is 100 pounds.",
      limitation: true,
    },
    {
      id: "ops-mc-043",
      category: "Fuel Limits",
      topic: "Aerobatics",
      difficulty: "high",
      question: "What is the minimum fuel per side for aerobatics?",
      options: ["100 lbs", "125 lbs", "150 lbs", "200 lbs"],
      correctAnswer: 2,
      explanation: "Minimum fuel for aerobatics is 150 pounds per side.",
      limitation: true,
    },

    // Runway
    {
      id: "ops-mc-044",
      category: "Runway Limits",
      topic: "LDA",
      difficulty: "medium",
      question: "What is the minimum Landing Distance Available (LDA)?",
      options: ["3,000 ft", "3,500 ft", "4,000 ft", "5,000 ft"],
      correctAnswer: 2,
      explanation: "Minimum LDA is 4,000 feet, or heavy weight flaps up landing distance plus 500 feet, whichever is greater.",
      limitation: true,
    },
    {
      id: "ops-mc-045",
      category: "Runway Limits",
      topic: "Width",
      difficulty: "medium",
      question: "What is the minimum runway width?",
      options: ["50 ft", "60 ft", "75 ft", "100 ft"],
      correctAnswer: 2,
      explanation: "Minimum runway width is 75 feet.",
      limitation: true,
    },

    // Winds
    {
      id: "ops-mc-046",
      category: "Wind Limits",
      topic: "Dry Runway",
      difficulty: "medium",
      question: "What is the maximum crosswind on a dry runway?",
      options: ["15 kts", "20 kts", "25 kts", "30 kts"],
      correctAnswer: 2,
      explanation: "Maximum crosswind on dry runway is 25 knots.",
      limitation: true,
    },
    {
      id: "ops-mc-047",
      category: "Wind Limits",
      topic: "Wet Runway",
      difficulty: "high",
      question: "What is the maximum crosswind on a wet runway?",
      options: ["5 kts", "10 kts", "15 kts", "20 kts"],
      correctAnswer: 1,
      explanation: "Maximum crosswind on wet runway is 10 knots.",
      limitation: true,
    },
    {
      id: "ops-mc-048",
      category: "Wind Limits",
      topic: "Icy Runway",
      difficulty: "high",
      question: "What is the maximum crosswind on an icy runway?",
      options: ["0 kts", "5 kts", "10 kts", "15 kts"],
      correctAnswer: 1,
      explanation: "Maximum crosswind on icy runway is 5 knots.",
      limitation: true,
    },
    {
      id: "ops-mc-049",
      category: "Wind Limits",
      topic: "Touch-and-Go",
      difficulty: "medium",
      question: "What is the maximum crosswind for touch-and-go operations?",
      options: ["15 kts", "20 kts", "25 kts", "30 kts"],
      correctAnswer: 1,
      explanation: "Maximum crosswind for touch-and-go is 20 knots.",
      limitation: true,
    },
    {
      id: "ops-mc-050",
      category: "Wind Limits",
      topic: "Formation",
      difficulty: "medium",
      question: "What is the maximum crosswind for formation takeoff/landing?",
      options: ["10 kts", "15 kts", "20 kts", "25 kts"],
      correctAnswer: 1,
      explanation: "Maximum crosswind for formation takeoff/landing is 15 knots.",
      limitation: true,
    },
    {
      id: "ops-mc-051",
      category: "Wind Limits",
      topic: "Tailwind",
      difficulty: "medium",
      question: "What is the maximum tailwind component for takeoff?",
      options: ["5 kts", "10 kts", "15 kts", "20 kts"],
      correctAnswer: 1,
      explanation: "Maximum tailwind component for takeoff is 10 knots.",
      limitation: true,
    },
    {
      id: "ops-mc-052",
      category: "Wind Limits",
      topic: "Canopy",
      difficulty: "medium",
      question: "What is the maximum wind with canopy open?",
      options: ["20 kts", "30 kts", "40 kts", "50 kts"],
      correctAnswer: 2,
      explanation: "Maximum wind with canopy open is 40 knots.",
      limitation: true,
    },

    // Acceleration Limits
    {
      id: "ops-mc-053",
      category: "G Limits",
      topic: "Symmetric Clean",
      difficulty: "high",
      question: "What are the symmetric G limits in clean configuration?",
      options: ["-2.0 to +5.0 Gs", "-3.0 to +6.0 Gs", "-3.5 to +7.0 Gs", "-4.0 to +8.0 Gs"],
      correctAnswer: 2,
      explanation: "Symmetric clean configuration G limits are -3.5 to +7.0 Gs.",
      limitation: true,
    },
    {
      id: "ops-mc-054",
      category: "G Limits",
      topic: "Symmetric Gear/Flaps",
      difficulty: "high",
      question: "What are the symmetric G limits with gear/flaps extended?",
      options: ["-1.0 to +2.0 Gs", "0 to +2.5 Gs", "0 to +3.0 Gs", "-0.5 to +3.5 Gs"],
      correctAnswer: 1,
      explanation: "Symmetric gear/flaps G limits are 0 to +2.5 Gs.",
      limitation: true,
    },
    {
      id: "ops-mc-055",
      category: "G Limits",
      topic: "Asymmetric Clean",
      difficulty: "high",
      question: "What are the asymmetric G limits in clean configuration?",
      options: ["-1.0 to +4.0 Gs", "-1.0 to +4.7 Gs", "-2.0 to +5.0 Gs", "-2.0 to +5.7 Gs"],
      correctAnswer: 1,
      explanation: "Asymmetric clean configuration G limits are -1.0 to +4.7 Gs.",
      limitation: true,
    },
    {
      id: "ops-mc-056",
      category: "G Limits",
      topic: "Asymmetric Gear/Flaps",
      difficulty: "high",
      question: "What are the asymmetric G limits with gear/flaps extended?",
      options: ["0 to +1.5 Gs", "0 to +2.0 Gs", "0 to +2.5 Gs", "-0.5 to +2.5 Gs"],
      correctAnswer: 1,
      explanation: "Asymmetric gear/flaps G limits are 0 to +2.0 Gs.",
      limitation: true,
    },

    // Intentional Spin Entry
    {
      id: "ops-mc-057",
      category: "Spin Limits",
      topic: "Entry Altitude",
      difficulty: "critical",
      question: "What is the minimum altitude for intentional spin entry?",
      options: ["10,000 ft MSL", "12,000 ft MSL", "13,500 ft MSL", "15,000 ft MSL"],
      correctAnswer: 2,
      explanation: "Minimum altitude for intentional spin entry is 13,500 feet MSL.",
      limitation: true,
    },
    {
      id: "ops-mc-058",
      category: "Spin Limits",
      topic: "Cloud Clearance",
      difficulty: "critical",
      question: "What is the minimum cloud clearance for spins?",
      options: ["1,000 ft", "3,000 ft", "5,000 ft", "7,000 ft"],
      correctAnswer: 3,
      explanation: "Minimum cloud clearance for spins is 7,000 feet above clouds.",
      limitation: true,
    },

    // Icing
    {
      id: "ops-mc-059",
      category: "Icing Limits",
      topic: "Band",
      difficulty: "high",
      question: "What is the maximum icing band thickness?",
      options: ["1,000 ft", "3,000 ft", "5,000 ft", "10,000 ft"],
      correctAnswer: 2,
      explanation: "Maximum icing band is 5,000 feet.",
      limitation: true,
    },
    {
      id: "ops-mc-060",
      category: "Icing Limits",
      topic: "Type",
      difficulty: "high",
      question: "What is the maximum icing type permitted?",
      options: ["Light rime", "Moderate rime", "Light clear", "Moderate clear"],
      correctAnswer: 0,
      explanation: "Maximum icing type is light rime.",
      limitation: true,
    },

    // Temperature
    {
      id: "ops-mc-061",
      category: "Temperature Limits",
      topic: "Ground Operations",
      difficulty: "medium",
      question: "What are the ambient temperature limits for ground operations?",
      options: ["-30 to +50°C", "-23 to +43°C", "-20 to +40°C", "-15 to +45°C"],
      correctAnswer: 1,
      explanation: "Ground operation is limited to ambient temperatures of -23 to +43°C.",
      limitation: true,
    },
  ],

  trueFalse: [
    {
      id: "ops-tf-001",
      category: "Prohibited Maneuvers",
      topic: "Spins",
      difficulty: "critical",
      question: "Inverted spins are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Inverted spins are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-002",
      category: "Prohibited Maneuvers",
      topic: "Spins",
      difficulty: "critical",
      question: "Inverted stalls are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Inverted stalls are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-003",
      category: "Prohibited Maneuvers",
      topic: "Spins",
      difficulty: "critical",
      question: "Aggravated spins past 2 turns are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Aggravated spins past 2 turns are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-004",
      category: "Prohibited Maneuvers",
      topic: "Spins",
      difficulty: "critical",
      question: "Spins with the PCL above idle are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Spins with the PCL above idle are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-005",
      category: "Prohibited Maneuvers",
      topic: "Configuration",
      difficulty: "critical",
      question: "Spins with landing gear, flaps, or speed brake extended are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Spins with landing gear, flaps, or speed brake extended are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-006",
      category: "Prohibited Maneuvers",
      topic: "Systems",
      difficulty: "critical",
      question: "Spins with the PMU off are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Spins with the PMU off are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-007",
      category: "Prohibited Maneuvers",
      topic: "Maneuvers",
      difficulty: "critical",
      question: "Abrupt cross-controlled (snap) maneuvers are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Abrupt cross-controlled (snap) maneuvers are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-008",
      category: "Prohibited Maneuvers",
      topic: "Maneuvers",
      difficulty: "critical",
      question: "Tail slides are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Tail slides are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-009",
      category: "Prohibited Maneuvers",
      topic: "Fuel",
      difficulty: "high",
      question: "Aerobatic maneuvers with greater than 50 pounds fuel imbalance are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Aerobatic maneuvers, spins, or stalls with greater than 50 pounds fuel imbalance are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-010",
      category: "Airspeed Limits",
      topic: "Rudder",
      difficulty: "high",
      question: "Full rudder deflection above 150 KIAS will exceed rudder control system limits.",
      correctAnswer: true,
      explanation: "TRUE. Full rudder deflection above 150 KIAS will exceed the limits of the rudder control system.",
      limitation: true,
    },
    {
      id: "ops-tf-011",
      category: "Engine Limits",
      topic: "Np",
      difficulty: "high",
      question: "Stabilized ground operations from 62 to 80% Np should be avoided.",
      correctAnswer: true,
      explanation: "TRUE. Avoid stabilized ground operations from 62 to 80% Np.",
      limitation: true,
    },
    {
      id: "ops-tf-012",
      category: "Spin Limits",
      topic: "Altitude",
      difficulty: "critical",
      question: "Spins below 10,000 feet pressure altitude are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Spins below 10,000 feet pressure altitude are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-013",
      category: "Spin Limits",
      topic: "Altitude",
      difficulty: "critical",
      question: "Spins above 22,000 feet pressure altitude are prohibited.",
      correctAnswer: true,
      explanation: "TRUE. Spins above 22,000 feet pressure altitude are prohibited.",
      limitation: true,
    },
    {
      id: "ops-tf-014",
      category: "Temperature Limits",
      topic: "Ground Ops",
      difficulty: "medium",
      question: "Ground operations are limited to -23 to +43°C ambient temperature.",
      correctAnswer: true,
      explanation: "TRUE. Ground operation is limited to ambient temperatures of -23 to +43°C.",
      limitation: true,
    },
    {
      id: "ops-tf-015",
      category: "Icing Limits",
      topic: "Type",
      difficulty: "high",
      question: "The maximum icing type is light rime.",
      correctAnswer: true,
      explanation: "TRUE. Maximum icing type is light rime.",
      limitation: true,
    },
  ],
};

export function getLimitationQuestions() {
  return [
    ...opsLimitsQuestions.multipleChoice,
    ...opsLimitsQuestions.trueFalse,
  ];
}
